USER-SUPPLIED VALUES:
config:
  clickhouseCluster: '{cluster}'
  clickhouseHost: cluster-pro-xdr-ck.ck.svc.cluster.local:8123
  clickhousePassword: t5K0RKYBePja49CPQ9TJ
  clickhousePasswordFile: /app/secret/ck-secret/password
  clickhouseUser: root
image: proxy.harbor/local-xdr/ck-exporter:master-20250715124145-a7afe3e9
podAnnotations:
  deployTime: "20260109070844"
priorityClassName: service-cluster-low
pullPolicy: IfNotPresent
replicaCount: 1
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
