USER-SUPPLIED VALUES:
annotations:
  deployTime: "20251016072122"
global:
  imageRegistry: proxy.harbor
  storageClass: local-ssd-storage
image:
  registry: proxy.harbor
  repository: local-xdr/zookeeper
  tag: 3.8.0-debian-10-r64
persistence:
  dataLogDir:
    size: 8Gi
  size: 8Gi
podAnnotations:
  deployTime: "20251016072122"
priorityClassName: service-node-critical
replicaCount: 3
resources:
  limits:
    cpu: 3
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
